### ISSUE TITLE
Table referencing in Models / Entities

### ISSUE THREAD

**Issue by bllivingston** [ortus-docs/quick-docs#27]
This is a suggestion from a newbie to ColdBox and ORM. It was confusing to me how CFCs using ORM in ColdBox were referencing tables until I came across the below explanation in Quick docs. This info should be in multiple places (outside of Quick) and probably highlighted within every Model CFC example especially in the getting started examples. The code reference in the Model CFC of 'table="contacts"' apparently was not a enough to knock it into my thick skull. In my case, it would have saved me some time and avoided confusion. 

Here are a few suggestions in areas of the documentation. I'd be happy to make pull requests if you all agree.
https://coldbox.ortusbooks.com/the-basics/models/coding-activeentity-style/contact.cfc
https://coldbox.ortusbooks.com/the-basics/models/coding-virtual-service-layer/contacts.cfc

"We don't need to tell Quick what table name to use for our entity. By default, Quick uses the pluralized name of the component for the table name. That means for our User entity Quick will assume the table name is users. You can override this by specifying a table metadata attribute on the component."
Reference: https://quick.ortusbooks.com/guide-1/getting-started/defining-an-entity#tables

**Comment by elpete** [comment]
I’m curious - are you suggesting additions to these docs or to cbORM?

**Comment by bllivingston** [comment]
I'm using the Quick docs as a reference to recommend editing other docs (not Quick). The explanation in Quick documentation regarding table reference is helpful. I feel it should be used as an example to implement inside other documentation like the URLs I previously referenced. Specifically, anything related to newbies (i.e. Getting Started instruction). Yes, cbORM would also be a location I would suggest to be edited.
